import com.xuncorp.spw.workshop.gradle.PluginPermission
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.4.20'
    id 'org.jetbrains.kotlin.kapt' version '2.4.20'
    id 'com.xuncorp.spw.workshop' version '0.1.0-dev21'
}

group = 'com.gg.SaltDiscordPlugin'
version = '0.0.7'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    google()
    maven {
        url = 'https://jitpack.io'
    }
}

dependencies {
    // https://mvnrepository.com/artifact/software.amazon.awssdk/s3
    implementation 'software.amazon.awssdk:s3:2.32.30'
    // JitPack 发什么神经 File not found, Build OK, 先自己构建个jar放libs里
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation files('libs/discord-game-sdk4j-1.0.0.jar')
    compileOnly "com.github.Moriafly:spw-workshop-api:0.1.0-dev21"
    kapt "com.github.Moriafly:spw-workshop-api:0.1.0-dev21"

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

def pluginClass = "com.gg.SaltDiscordPlugin.MainPlugin"
def pluginId = "com.gg.SaltDiscordPlugin"
def pluginName = "Discord 丰富状态"
def pluginVersion = version
def pluginDescription = "在Discord中显示 SPW 丰富状态"
def pluginProvider = "GaodaGG & zmxlsss666"
def pluginOpenSourceUrl = "https://github.com/GaodaGG/SaltDiscordPlugin"

spmod { config ->
    config.PluginClass = pluginClass
    config.PluginId = pluginId
    config.PluginName = pluginName
    config.PluginVersion = pluginVersion
    config.PluginDescription = pluginDescription
    config.PluginProvider = pluginProvider
    config.PluginOpenSourceUrl = pluginOpenSourceUrl
    config.PluginHasConfig = true
    config.PluginPermissions = [PluginPermission.LIBRARY_READ]
}